### ISSUE TITLE
Provide basic logging?

### ISSUE THREAD

**Issue by fast90** [fast90/christian#35]

**Comment by telegnom** [comment]
<pre>
syslog.openlog([ident[, logoption[, facility]]])

Priority levels (high to low):
    LOG_EMERG, LOG_ALERT, LOG_CRIT, LOG_ERR, LOG_WARNING, LOG_NOTICE, LOG_INFO, LOG_DEBUG.
Facilities:
    LOG_KERN, LOG_USER, LOG_MAIL, LOG_DAEMON, LOG_AUTH, LOG_LPR, LOG_NEWS, LOG_UUCP, LOG_CRON, LOG_SYSLOG and LOG_LOCAL0 to LOG_LOCAL7.
 syslog.syslog(message)
syslog.syslog(priority, message)
syslog.openlog([ident[, logoption[, facility]]])
syslog.closelog()
syslog.setlogmask(maskpri)
</pre>
