### ISSUE TITLE
handling reconnects and irc service outages

### ISSUE THREAD

**Issue by telegnom** [fast90/christian#42]
proper handling of reconnects, (callback handler with delay?)
handle round robin a-records properly 
handle irc service outages (nickserv/chanserv)
reauthentication after nickserv came back to life :)

Fast viel Spaß :stuck_out_tongue:

**Comment by fast90** [comment]
* proper handling of reconnects closed by 45aa157 wait some time and try to reconnect
* handle round robin a-records properly moved to #45
* handle irc service outages (nickserv/chanserv) moved to #46
* reauthentication after nickserv came back to life partially closed by 45aa157 . Bot tries to reconnect every time. Needs to check if authentication succeeded /fails. See #47
