### ISSUE TITLE
Continuous visible room status

### ISSUE THREAD

**Issue by schiermi** [fast90/christian#51]
Provide current room status without the need to issue commands.

Either update channel topic or send channel wide messages in response to commands which modify the room status.

To maintain clarity: Do not display individual member nicks in case more than $threshold members are in the room.

Up to threshold; display: "nick1, nick2, nick3"
Over threshold; display: "3+"

**Comment by fast90** [comment]
HQ status will be like:
HQ: Members (4) [2015-12-14 20:35]                                                                                                          HQ: Public (4) [2015-12-14 20:35]
HQ: Closed [2015-12-14 20:35]
