### ISSUE TITLE
implement a wischmopp for teh toilets

### ISSUE THREAD

**Issue by telegnom** [fast90/christian#53]
Alternative für die Kloreinigung: Wenn jemand den Bedarf danach sieht (ich denke der persönliche minimale Sauberkeitslevel variiert), gibt er "hans" Bescheid. Dieser wirft den Status "Toiletten brauchen Reinigung" einmal pro Tag in den Channel.

**Comment by fast90** [comment]
Lieber in den Channel werfen (und evtl. per query) wenn jemand das HQ öffnet?

**Comment by fast90** [comment]
Closed by 84512fe
